version: '3.8'

services:
  api:
    container_name: api_teste_backend
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 127.0.0.1:${API_PORT}:${API_PORT}
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    container_name: api_teste_backend_postgres
    image: postgres:13-alpine
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 127.0.0.1:${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - api_db_data:/var/lib/postgresql/data

networks:
  backend:
volumes:
  api_db_data:
