export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const USER_UNAUTHORIZED = 'USER_UNAUTHORIZED';

export const ROLE_NOT_FOUND = 'ROLE_NOT_FOUND';

export const USER_EXIST = 'USER_EXIST';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_PASSWORD_EMPTY = 'USER_PASSWORD_EMPTY';
export const USER_ROLE_NOT_FOUND = 'USER_ROLE_NOT_FOUND';
export const DUPLICATE_EMAIL = 'DUPLICATE_EMAIL';

export const PAYER_NOT_FOUND = 'PAYER_NOT_FOUND';
export const PAYEE_NOT_FOUND = 'PAYEE_NOT_FOUND';
export const BALANCE_INSUFFICIENT = 'BALANCE_INSUFFICIENT';
